### ISSUE TITLE
decadojo.coderdojo.jp を GitHub Pages に移行する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/decadojo.coderdojo.jp#1]
[decadojo.coderdojo.jp](http://decadojo.coderdojo.jp/) を運営している常田さんから許諾をいただいて、現在 GitHub Pages に移行しています 🚜 💨 ✨ 

特に急ぎではないですが、次の部分がまだ未完了なのでお手隙の際にサポートしていただけると嬉しいです...!! (＞人＜ )💖

読んで欲しい人: @yuki384 @Yuppymam @chicaco

## 移行までの流れ

- [x] [CoderDojo 所沢](https://www.facebook.com/CoderDojoTokorozawa/)の常田さんと方向性を決める (移行する方向性で合致)
- [x] [decadojo.coderdojo.jp](http://decadojo.coderdojo.jp/) のWebサイトのソースコードを解析する
- [x] [decadojo.coderdojo.jp](http://decadojo.coderdojo.jp/) の [Theme (ORION)](https://design-plus1.com/tcd-w/tcd037) ライセンスを購入する
- [x] Theme (ORION) の[利用規約](https://design-plus1.com/tcd-w/license_standard)を README に追記する
- [x] Jekyll でサイトを制作し、GitHub Pages で公開する
- [x] GitHub Pages の Custom Subdomain を設定する => https://decadojo-dev.coderdojo.jp/
- [x] デザイン上の見た目の違いを探し、ズレを洗い出す
   - 移行元: http://decadojo.coderdojo.jp/ (SSL 非対応)
   - 移行先: https://decadojo-dev.coderdojo.jp/
- [x] 上記で洗い出したズレを随時修正していく
   - [x] ヘッダーに DecaDojo ロゴが表示されてしまう
   - [x] レスポンシブデザインが適用されていない...?
   - [x] www-widgetapi.js でエラーが発生する (これは移行元も同じなので対応しなくても良さそう)

**Comment by yuki384** [comment]
レスポンシブデザインが適用されていない件ですが、[テーマのデモサイト](https://tcd-theme.com/tcd037)を見るとテーマの仕様も影響していそうです。一応、 https://github.com/coderdojo-japan/decadojo/commit/5b8306b0981e57a92d1168369a439e428cae1d36 で見た目上はあまり崩れないように変更しました。

「 ヘッダーに DecaDojo ロゴが表示されてしまう問題」も同じ仕様による問題のようです。
解決を頑張ってはみましたが、ヘッダーを消すのが一番良さそうと思います。いかがでしょうか？

**Comment by yasulab** [comment]
> ヘッダーを消すのが一番良さそうと思います。いかがでしょうか？

調査ありがとうございます！ひとまずはこれで対応してみましょう！d(￣ ￣)✨

**Comment by yasulab** [comment]
トップページに分かりやすいロゴ画像が貼ってあるので、あとは h1 タグや img alt 属性などに注意してアクセシビリティー的に問題なさそうなら大丈夫かなと考えています 🙆‍♂️ 🆗 ✨

**Comment by yasulab** [comment]
トップページに分かりやすいロゴ画像が貼ってあるので、あとは h1 タグや img alt 属性などに注意してアクセシビリティー的に問題なさそうなら大丈夫かなと考えています 🙆‍♂️ 🆗 ✨ 

![image](https://user-images.githubusercontent.com/155807/90599568-0e090080-e230-11ea-84a0-710fc0c70389.png)

**Comment by yuki384** [comment]
https://github.com/coderdojo-japan/decadojo/pull/2 でヘッダーを削除しました✅

**Comment by yasulab** [comment]
こちら無事リリースしました！対応ありがとうございました！！(＞人＜ )💖
https://decadojo.coderdojo.jp/
